##################### ElasticSearch Configuration Example #####################
# http://elasticsearch.org/guide/en/elasticsearch/reference/current/setup-configuration.html

################################### Cluster ###################################

cluster.name: stagex_search

#################################### Node #####################################

# Node names are generated dynamically on startup, so you're relieved
# from configuring them manually. You can tie this node to a specific name:
#
node.name: stage_search-01

#################################### Index ####################################

index.number_of_shards: 5
index.number_of_replicas: 2

################################### Memory ####################################

# bootstrap.mlockall: true

################################### Gateway ###################################
# http://elasticsearch.org/guide/en/elasticsearch/reference/current/modules-gateway.html
# gateway.type: local
# gateway.recover_after_nodes: 1
# gateway.recover_after_time: 5m
# gateway.expected_nodes: 2

################################## Discovery ##################################
# http://elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html

discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.timeout: 3s

discovery.zen.ping.multicast.enabled: false
# discovery.zen.ping.unicast.hosts: ["host1", "host2:port"]

#cloud:
#    aws:
#        access_key: AKIAICYRUYXAXE3MTUXA
#        secret_key: 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
#        region: us-west-2
#discovery:
#    type: ec2

################################## Slow Log ##################################

# Shard level query and fetch threshold logging.

#index.search.slowlog.threshold.query.warn: 10s
#index.search.slowlog.threshold.query.info: 5s
#index.search.slowlog.threshold.query.debug: 2s
#index.search.slowlog.threshold.query.trace: 500ms

#index.search.slowlog.threshold.fetch.warn: 1s
#index.search.slowlog.threshold.fetch.info: 800ms
#index.search.slowlog.threshold.fetch.debug: 500ms
#index.search.slowlog.threshold.fetch.trace: 200ms

#index.indexing.slowlog.threshold.index.warn: 10s
#index.indexing.slowlog.threshold.index.info: 5s
#index.indexing.slowlog.threshold.index.debug: 2s
#index.indexing.slowlog.threshold.index.trace: 500ms