<?php
$timezones[] = array("abbr"=>"ACDT","name"=>"Australian Central Daylight Time","offset"=>"+10:30");
$timezones[] = array("abbr"=>"ACST","name"=>"Australian Central Standard Time","offset"=>"+9:30");
$timezones[] = array("abbr"=>"ACT","name"=>"ASEAN Common Time","offset"=>"+8");
$timezones[] = array("abbr"=>"ADT","name"=>"Atlantic Daylight Time","offset"=>"-3");
$timezones[] = array("abbr"=>"AEDT","name"=>"Australian Eastern Daylight Time","offset"=>"+11");
$timezones[] = array("abbr"=>"AEST","name"=>"Australian Eastern Standard Time","offset"=>"+10");
$timezones[] = array("abbr"=>"AFT","name"=>"Afghanistan Time","offset"=>"+4:30");
$timezones[] = array("abbr"=>"AKDT","name"=>"Alaska Daylight Time","offset"=>"-8");
$timezones[] = array("abbr"=>"AKST","name"=>"Alaska Standard Time","offset"=>"-9");
$timezones[] = array("abbr"=>"AMST","name"=>"Armenia Summer Time","offset"=>"+5");
$timezones[] = array("abbr"=>"AMT","name"=>"Armenia Time","offset"=>"+4");
$timezones[] = array("abbr"=>"ART","name"=>"Argentina Time","offset"=>"-3");
$timezones[] = array("abbr"=>"AST","name"=>"Arab Standard Time (Kuwait, Riyadh)","offset"=>"+3");
$timezones[] = array("abbr"=>"AST","name"=>"Arabian Standard Time (Abu Dhabi, Muscat)","offset"=>"+4");
$timezones[] = array("abbr"=>"AST","name"=>"Arabic Standard Time (Baghdad)","offset"=>"+3");
$timezones[] = array("abbr"=>"AST","name"=>"Atlantic Standard Time","offset"=>"-4");
$timezones[] = array("abbr"=>"AWDT","name"=>"Australian Western Daylight Time","offset"=>"+9");
$timezones[] = array("abbr"=>"AWST","name"=>"Australian Western Standard Time","offset"=>"+8");
$timezones[] = array("abbr"=>"AZOST","name"=>"Azores Standard Time","offset"=>"-1");
$timezones[] = array("abbr"=>"AZT","name"=>"Azerbaijan Time","offset"=>"+4");
$timezones[] = array("abbr"=>"BDT","name"=>"Brunei Time","offset"=>"+8");
$timezones[] = array("abbr"=>"BIOT","name"=>"British Indian Ocean Time","offset"=>"+6");
$timezones[] = array("abbr"=>"BIT","name"=>"Baker Island Time","offset"=>"-12");
$timezones[] = array("abbr"=>"BOT","name"=>"Bolivia Time","offset"=>"-4");
$timezones[] = array("abbr"=>"BRT","name"=>"Brasilia Time","offset"=>"-3");
$timezones[] = array("abbr"=>"BST","name"=>"Bangladesh Standard Time","offset"=>"+6");
$timezones[] = array("abbr"=>"BTT","name"=>"Bhutan Time","offset"=>"+6");
$timezones[] = array("abbr"=>"CAT","name"=>"Central Africa Time","offset"=>"+2");
$timezones[] = array("abbr"=>"CCT","name"=>"Cocos Islands Time","offset"=>"+6:30");
$timezones[] = array("abbr"=>"CDT","name"=>"Central Daylight Time (North America)","offset"=>"-5");
$timezones[] = array("abbr"=>"CEDT","name"=>"Central European Daylight Time","offset"=>"+2");
$timezones[] = array("abbr"=>"CET","name"=>"Central European Time","offset"=>"+1");
$timezones[] = array("abbr"=>"CHAST","name"=>"Chatham Standard Time","offset"=>"+12:45");
$timezones[] = array("abbr"=>"CIST","name"=>"Clipperton Island Standard Time","offset"=>"-8");
$timezones[] = array("abbr"=>"CKT","name"=>"Cook Island Time","offset"=>"-10");
$timezones[] = array("abbr"=>"CLST","name"=>"Chile Summer Time","offset"=>"-3");
$timezones[] = array("abbr"=>"CLT","name"=>"Chile Standard Time","offset"=>"-4");
$timezones[] = array("abbr"=>"COST","name"=>"Colombia Summer Time","offset"=>"-4");
$timezones[] = array("abbr"=>"COT","name"=>"Colombia Time","offset"=>"-5");
$timezones[] = array("abbr"=>"CST","name"=>"Central Standard Time (North America)","offset"=>"-6");
$timezones[] = array("abbr"=>"CST","name"=>"China Standard Time","offset"=>"+8");
$timezones[] = array("abbr"=>"CVT","name"=>"Cape Verde Time","offset"=>"-1");
$timezones[] = array("abbr"=>"CXT","name"=>"Christmas Island Time","offset"=>"+7");
$timezones[] = array("abbr"=>"ChST","name"=>"Chamorro Standard Time","offset"=>"+10");
$timezones[] = array("abbr"=>"DFT","name"=>"AIX Central European Time","offset"=>"+1");
$timezones[] = array("abbr"=>"EAST","name"=>"Easter Island Standard Time","offset"=>"-6");
$timezones[] = array("abbr"=>"EAT","name"=>"East Africa Time","offset"=>"+3");
$timezones[] = array("abbr"=>"ECT","name"=>"Eastern Caribbean Time","offset"=>"-4");
$timezones[] = array("abbr"=>"ECT","name"=>"Ecuador Time","offset"=>"-5");
$timezones[] = array("abbr"=>"EDT","name"=>"Eastern Daylight Time (North America)","offset"=>"-4");
$timezones[] = array("abbr"=>"EEDT","name"=>"Eastern European Daylight Time","offset"=>"+3");
$timezones[] = array("abbr"=>"EEST","name"=>"Eastern European Summer Time","offset"=>"+3");
$timezones[] = array("abbr"=>"EET","name"=>"Eastern European Time","offset"=>"+2");
$timezones[] = array("abbr"=>"EST","name"=>"Eastern Standard Time (North America)","offset"=>"-5");
$timezones[] = array("abbr"=>"FJT","name"=>"Fiji Time","offset"=>"+12");
$timezones[] = array("abbr"=>"FKST","name"=>"Falkland Islands Standard Time","offset"=>"-4");
$timezones[] = array("abbr"=>"GALT","name"=>"Galapagos Time","offset"=>"-6");
$timezones[] = array("abbr"=>"GET","name"=>"Georgia Standard Time","offset"=>"+4");
$timezones[] = array("abbr"=>"GFT","name"=>"French Guiana Time","offset"=>"-3");
$timezones[] = array("abbr"=>"GILT","name"=>"Gilbert Island Time","offset"=>"+12");
$timezones[] = array("abbr"=>"GIT","name"=>"Gambier Island Time","offset"=>"-9");
$timezones[] = array("abbr"=>"GMT","name"=>"Greenwich Mean Time","offset"=>"0");
$timezones[] = array("abbr"=>"GST","name"=>"South Georgia and the South Sandwich Islands","offset"=>"-2");
$timezones[] = array("abbr"=>"GYT","name"=>"Guyana Time","offset"=>"-4");
$timezones[] = array("abbr"=>"HADT","name"=>"Hawaii-Aleutian Daylight Time","offset"=>"-9");
$timezones[] = array("abbr"=>"HAST","name"=>"Hawaii-Aleutian Standard Time","offset"=>"-10");
$timezones[] = array("abbr"=>"HKT","name"=>"Hong Kong Time","offset"=>"+8");
$timezones[] = array("abbr"=>"HMT","name"=>"Heard and McDonald Islands Time","offset"=>"+5");
$timezones[] = array("abbr"=>"HST","name"=>"Hawaii Standard Time","offset"=>"-10");
$timezones[] = array("abbr"=>"IRKT","name"=>"Irkutsk Time","offset"=>"+8");
$timezones[] = array("abbr"=>"IRST","name"=>"Iran Standard Time","offset"=>"+3:30");
$timezones[] = array("abbr"=>"IST","name"=>"Indian Standard Time","offset"=>"+5:30");
$timezones[] = array("abbr"=>"IST","name"=>"Irish Summer Time","offset"=>"+1");
$timezones[] = array("abbr"=>"IST","name"=>"Israel Standard Time","offset"=>"+2");
$timezones[] = array("abbr"=>"JST","name"=>"Japan Standard Time","offset"=>"+9");
$timezones[] = array("abbr"=>"KRAT","name"=>"Krasnoyarsk Time","offset"=>"+7");
$timezones[] = array("abbr"=>"KST","name"=>"Korea Standard Time","offset"=>"+9");
$timezones[] = array("abbr"=>"LHST","name"=>"Lord Howe Standard Time","offset"=>"+10:30");
$timezones[] = array("abbr"=>"LINT","name"=>"Line Islands Time","offset"=>"+14");
$timezones[] = array("abbr"=>"MAGT","name"=>"Magadan Time","offset"=>"+11");
$timezones[] = array("abbr"=>"MDT","name"=>"Mountain Daylight Time (North America)","offset"=>"-6");
$timezones[] = array("abbr"=>"MIT","name"=>"Marquesas Islands Time","offset"=>"-9:30");
$timezones[] = array("abbr"=>"MSD","name"=>"Moscow Summer Time","offset"=>"+4");
$timezones[] = array("abbr"=>"MSK","name"=>"Moscow Standard Time","offset"=>"+3");
$timezones[] = array("abbr"=>"MST","name"=>"Malaysian Standard Time","offset"=>"+8");
$timezones[] = array("abbr"=>"MST","name"=>"Mountain Standard Time (North America)","offset"=>"-7");
$timezones[] = array("abbr"=>"MST","name"=>"Myanmar Standard Time","offset"=>"+6:30");
$timezones[] = array("abbr"=>"MUT","name"=>"Mauritius Time","offset"=>"+4");
$timezones[] = array("abbr"=>"NDT","name"=>"Newfoundland Daylight Time","offset"=>"-2:30");
$timezones[] = array("abbr"=>"NFT","name"=>"Norfolk Time","offset"=>"+11:30");
$timezones[] = array("abbr"=>"NPT","name"=>"Nepal Time","offset"=>"+5:45");
$timezones[] = array("abbr"=>"NST","name"=>"Newfoundland Standard Time","offset"=>"-3:30");
$timezones[] = array("abbr"=>"NT","name"=>"Newfoundland Time","offset"=>"-3:30");
$timezones[] = array("abbr"=>"OMST","name"=>"Omsk Time","offset"=>"+6");
$timezones[] = array("abbr"=>"PDT","name"=>"Pacific Daylight Time (North America)","offset"=>"-7");
$timezones[] = array("abbr"=>"PETT","name"=>"Kamchatka Time","offset"=>"+12");
$timezones[] = array("abbr"=>"PHOT","name"=>"Phoenix Island Time","offset"=>"+13");
$timezones[] = array("abbr"=>"PKT","name"=>"Pakistan Standard Time","offset"=>"+5");
$timezones[] = array("abbr"=>"PST","name"=>"Pacific Standard Time (North America)","offset"=>"-8");
$timezones[] = array("abbr"=>"PST","name"=>"Philippine Standard Time","offset"=>"+8");
$timezones[] = array("abbr"=>"RET","name"=>"Réunion Time","offset"=>"+4");
$timezones[] = array("abbr"=>"SAMT","name"=>"Samara Time","offset"=>"+4");
$timezones[] = array("abbr"=>"SAST","name"=>"South African Standard Time","offset"=>"+2");
$timezones[] = array("abbr"=>"SBT","name"=>"Solomon Islands Time","offset"=>"+11");
$timezones[] = array("abbr"=>"SCT","name"=>"Seychelles Time","offset"=>"+4");
$timezones[] = array("abbr"=>"SLT","name"=>"Sri Lanka Time","offset"=>"+5:30");
$timezones[] = array("abbr"=>"SST","name"=>"Samoa Standard Time","offset"=>"-11");
$timezones[] = array("abbr"=>"SST","name"=>"Singapore Standard Time","offset"=>"+8");
$timezones[] = array("abbr"=>"TAHT","name"=>"Tahiti Time","offset"=>"-10");
$timezones[] = array("abbr"=>"THA","name"=>"Thailand Standard Time","offset"=>"+7");
$timezones[] = array("abbr"=>"UTC","name"=>"Coordinated Universal Time","offset"=>"0");
$timezones[] = array("abbr"=>"UYST","name"=>"Uruguay Summer Time","offset"=>"-2");
$timezones[] = array("abbr"=>"UYT","name"=>"Uruguay Standard Time","offset"=>"-3");
$timezones[] = array("abbr"=>"VET","name"=>"Venezuelan Standard Time","offset"=>"-4:30");
$timezones[] = array("abbr"=>"VLAT","name"=>"Vladivostok Time","offset"=>"+10");
$timezones[] = array("abbr"=>"WAT","name"=>"West Africa Time","offset"=>"+1");
$timezones[] = array("abbr"=>"WEDT","name"=>"Western European Daylight Time","offset"=>"+1");
$timezones[] = array("abbr"=>"WET","name"=>"Western European Time","offset"=>"0");
$timezones[] = array("abbr"=>"YAKT","name"=>"Yakutsk Time","offset"=>"+9");
$timezones[] = array("abbr"=>"YEKT","name"=>"Yekaterinburg Time","offset"=>"+5");